### PR TITLE
feat(dict): allow support of multi dictionaries and min length

### PR DESCRIPTION
**Pull request by yannickglt**
Allow to add dictionaries to the spell checker:

``` javascript
new JsSpellChecker({
  dicts: [
    {
      aff: __dirname + '/../node_modules/lintspelljs/dicts/en_US.aff',
      dic: __dirname + '/../node_modules/lintspelljs/dicts/en_US.dic'
    },
    __dirname + '/../dicts/english.dic',
    __dirname + '/../dicts/jetbrains.dic'
  ]
});
```

And allow to pass words less than a minimum length:

``` javascript
new JsSpellChecker({
  minLength: 4
});
```

With this parameter, words with a length less than _minLength_ will not be checked. It's useful for single-letter words.

### CODE REVIEW

**Comment by yannickglt** [comment]
Is there a chance to merge this pull request @aotaduy?

**Comment by aotaduy** [comment]
Thanks for the PR! give me some time to review it.

**Comment by yannickglt** [comment]
Thanks a lot! I am not sure about the way to import dictionaries. Reading the file from at the beginning might be simpler and more testable.
For example:

``` js
new JsSpellChecker({
  dicts: [
    {
      aff: fs.readFileSync(__dirname + '/../node_modules/lintspelljs/dicts/en_US.aff'),
      dic: fs.readFileSync(__dirname + '/../node_modules/lintspelljs/dicts/en_US.dic')
    },
    fs.readFileSync(__dirname + '/../dicts/english.dic'),
    fs.readFileSync(__dirname + '/../dicts/jetbrains.dic')
  ]
});
```

**Comment by aotaduy** [comment]
Hello, I'm ready to merge this one. I like this one more than the other (#3) since I'm not sure about the capitalize functionality.
Can you tell me what would be the case to use the capitalization. 

Best Regards

**Comment by yannickglt** [comment]
Hey!
I don't think capitalization is relevant anymore. I removed the pull request.
Thank you.

**Comment by aotaduy** [comment]
Thanks!

**Pull request merged**
